services:
  hotpotato: 
    container_name: hotpotato
    build:
      context: . # Specifies the directory containing your Dockerfile
      dockerfile: Dockerfile # Specifies the name of your Dockerfile (if it's not the default)
    ports:
      - "8880:8080" # Map host port 8880 to container port 8080
    networks:
      - mqnet
      - sibilas_net
    volumes:
      - /home/sibila-server/hotpotato/data:/app/data

networks:
  mqnet:
    external: true
  sibilas_net:
    external: true